# Generated by Django 5.0.6 on 2024-06-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cidade', models.IntegerField()),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=2)),
                ('coord_lat', models.FloatField()),
                ('coord_lon', models.FloatField()),
                ('populacao', models.IntegerField()),
                ('timezone', models.IntegerField()),
                ('nascer_sol', models.IntegerField()),
                ('baixar_sol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cidade', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
                ('timestamp_previsao', models.IntegerField()),
                ('condicao', models.CharField(max_length=255)),
                ('descricao_condicao', models.CharField(max_length=255)),
                ('temperatura', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('sensacao', models.FloatField()),
                ('umidade', models.IntegerField()),
                ('pressao', models.IntegerField()),
                ('direcao_vento', models.IntegerField()),
                ('velocidade_vento', models.FloatField()),
            ],
        ),
    ]
