# Generated by Django 5.0.6 on 2024-06-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta_armazena_mysql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsao',
            name='data_hora',
            field=models.CharField(max_length=50),
        ),
    ]
