services:
  # --------------------- Flask Framework Server ------------------
  weather:
    container_name: 'weather_api'
    build:
      context: ./flask/app/weather
      dockerfile: Dockerfile
      # image: weather_api
    env_file:
      - .env
    ports:
      - "5002:5002"       
    volumes:
      - ./flask/app/weather:/app
    depends_on:
      postgresql:
        condition: service_healthy
  
  newsletter:
    container_name: 'newsletter_api'
    build:
      context: ./flask/app/newsletter
      dockerfile: Dockerfile
      # image: newsletter_api
    env_file:
      - .env
    ports:
      - "5003:5003"      
    volumes:
      - ./flask/app/newsletter:/app
    depends_on:
      postgresql:
        condition: service_healthy


  # --------------------- Database Server e GUI ------------------
  postgresql:
    container_name: 'db'
    image: postgres:latest
    restart: always
    ports:
      - "7777:5432" # Pgadmin
      - "8887:5432" # Weather Service
      - "8877:5432" # Newsletter Service
    expose:
      - "5432"
    env_file:
      - .env
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: 'gui_db'
    image: dpage/pgadmin4:8.11
    ports:
      - "7778:80"
    env_file:
      - .env
